name: Run KataGo on CGOS

on:
  push:
    branches:
      - cgos
  workflow_dispatch:

jobs:
  run-katago:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CGOS branch
        uses: actions/checkout@v3
        with:
          ref: CGOS

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip dpkg git wget
          pip install requests

      - name: Run KataGo CGOS script
        run: |
          python3 main.py
